# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Francisco Rangel"
description: > # this means to ignore newlines until "email:"
   Blog and Portfolio

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/fr-logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Francisco Rangel'
author: 'Francisco Rangel'
author_image: "/assets/images/fr-portrait.jpg"

paginate:	5
host: "0.0.0.0"
url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: 

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
# - icon:	twitter
#   url:	https://twitter.com/dirkfabisch
#   desc: Follow me on twitter
#   share_url: http://twitter.com/share
#   share_title: ?text=
#   share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/francRang
    desc:	Visit my Github
    share_url: https://github.com/francRang
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
