# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Selim Bakdemir"
description: > # this means to ignore newlines until "email:"
   iOS Developer - Peak Games

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

email: selim.bakdemir@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Selim Bakdemir'
author: 'Selim Bakdemir'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://selim1377.github.io" # the base hostname & protocol for your site
baseurl: "http://selim1377.github.io"
#used to display twitter cards
twitter_handle: '@sbakdemir'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/sbakdemir
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/selim1377
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
