# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Dataflows blog"
description: > # this means to ignore newlines until "email:"
   When spreadsheets become apps.

email: hello@dataflows.io
#blog logo
logo: "/assets/images/icon.png"
logoColorful: "/assets/images/icon_violet.png"
# blog cover
cover: "/assets/images/hero-section-background.jpg"

name: 'Dataflows'
author: 'Dataflows'
author_image: "/assets/images/icon.png"

authors:
    marek:
        name: 'Marek Rogala'
        author: 'Marek Rogala'
        image: "/assets/images/author.jpg"
        bio: "CTO at Dataflows"
    filip:
        name: 'Filip Stachura'
        author: 'Filip Stachura'
        image: ""
    damian:
        name: 'Damian Rodziewicz'
        author: 'Damian Rodziewicz'
        image: '/assets/images/damian.jpg'
    pawel:
        name: 'Paweł Przytuła'
        author: 'Paweł Przytuła'
        image: ""
    krolek:
        name: 'Piotr Kroll'
        author: 'Piotr Kroll'
        image: ""

paginate:	5

url: "http://blog.dataflows.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/DataflowsIO
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dataflows
    desc:	Check out our github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
